// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSfAccount = "sf_account"

// SfAccount mapped from table <sf_account>
type SfAccount struct {
	ID                string `gorm:"column:Id" json:"Id"`
	DOTNumberC        string `gorm:"column:DOT_Number__c" json:"DOT_Number__c"`
	Name              string `gorm:"column:Name" json:"Name"`
	CRMAccountNumberC string `gorm:"column:CRM_Account_Number__c" json:"CRM_Account_Number__c"`
}

func (m SfAccount) GetId() string {
	return m.ID
}

// TableName SfAccount's table name
func (*SfAccount) TableName() string {
	return TableNameSfAccount
}
