// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSfCadenceDetails = "sf_cadence_details"

// SfCadenceDetails mapped from table <sf_cadence_details>
type SfCadenceDetails struct {
	Id                                      string       `gorm:"column:Id" json:"Id"`
	isDeleted                               bool         `gorm:"column:isDeleted" json:"isDeleted"`
	Name                                    string       `gorm:"column:Name" json:"Name"`
	CreatedDate                             time.Time    `gorm:"column:CreatedDate" json:"CreatedDate"`
	CreatedById                             string       `gorm:"column:CreatedById" json:"CreatedById"`
	LastModifiedDate                        time.Time    `gorm:"column:LastModifiedDate" json:"LastModifiedDate"`
	LastModifiedById                        string       `gorm:"column:LastModifiedById" json:"LastModifiedById"`
	SystemModstamp                          time.Time    `gorm:"column:SystemModstamp" json:"SystemModstamp"`
	LastViewedDate                          string       `gorm:"column:LastViewedDate" json:"LastViewedDate"`
	LastReferencedDate                      string       `gorm:"column:LastReferencedDate" json:"LastReferencedDate"`
	Factorsoft_Client_Number__c             string       `gorm:"column:Factorsoft_Client_Number__c" json:"Factorsoft_Client_Number__c"`
	First_Funding_Date__c                   time.Time    `gorm:"column:First_Funding_Date__c" json:"First_Funding_Date__c"`
	Last_Funding_Date__c                    time.Time    `gorm:"column:Last_Funding_Date__c" json:"Last_Funding_Date__c"`
	Balance__c                              float64      `gorm:"column:Balance__c" json:"Balance__c"`
	Active__c                               bool         `gorm:"column:Active__c" json:"Active__c"`
	Sub_Account__c                          string       `gorm:"column:Sub_Account__c" json:"Sub_Account__c"`
	Legacy_CRM_ID__c                        string       `gorm:"column:Legacy_CRM_ID__c" json:"Legacy_CRM_ID__c"`
	Opportunity__c                          string       `gorm:"column:Opportunity__c" json:"Opportunity__c"`
	Account__c                              string       `gorm:"column:Account__c" json:"Account__c"`
	Factorsoft_Client_Key__c                float64      `gorm:"column:Factorsoft_Client_Key__c" json:"Factorsoft_Client_Key__c"`
	Exit_Reason__c                          string       `gorm:"column:Exit_Reason__c" json:"Exit_Reason__c"`
	Client_Setup_Sent_to_RTS_Pro__c         bool         `gorm:"column:Client_Setup_Sent_to_RTS_Pro__c" json:"Client_Setup_Sent_to_RTS_Pro__c"`
	Exit_Notes__c                           string       `gorm:"column:Exit_Notes__c" json:"Exit_Notes__c"`
	Fuel_Card_Group_Code__c                 string       `gorm:"column:Fuel_Card_Group_Code__c" json:"Fuel_Card_Group_Code__c"`
	Fuel_Status_Group_Code__c               string       `gorm:"column:Fuel_Status_Group_Code__c" json:"Fuel_Status_Group_Code__c"`
	Pilot_Travel_Centers_LLC_Broker_Code__c bool         `gorm:"column:Pilot_Travel_Centers_LLC_Broker_Code__c" json:"Pilot_Travel_Centers_LLC_Broker_Code__c"`
	Account_Rep__c                          string       `gorm:"column:Account_Rep__c" json:"Account_Rep__c"`
	Cadence_Operations_Manager__c           string       `gorm:"column:Cadence_Operations_Manager__c" json:"Cadence_Operations_Manager__c"`
	Cadence_Supervisor__c                   string       `gorm:"column:Cadence_Supervisor__c" json:"Cadence_Supervisor__c"`
	Client_Credit_Rating__c                 string       `gorm:"column:Client_Credit_Rating__c" json:"Client_Credit_Rating__c"`
	Competitor_Moved_To__c                  string       `gorm:"column:Competitor_Moved_To__c" json:"Competitor_Moved_To__c"`
	Exit_Code__c                            string       `gorm:"column:Exit_Code__c" json:"Exit_Code__c"`
	First_Fund_Exceptions__c                string       `gorm:"column:First_Fund_Exceptions__c" json:"First_Fund_Exceptions__c"`
	Last_Month_Volume__c                    float64      `gorm:"column:Last_Month_Volume__c" json:"Last_Month_Volume__c"`
	UCC_Filing_Group_Code__c                string       `gorm:"column:UCC_Filing_Group_Code__c" json:"UCC_Filing_Group_Code__c"`
	Value__c                                string       `gorm:"column:Value__c" json:"Value__c"`
	WO_Reason__c                            string       `gorm:"column:WO_Reason__c" json:"WO_Reason__c"`
	Write_Off__c                            string       `gorm:"column:Write_Off__c" json:"Write_Off__c"`
	Exit_Date__c                            string       `gorm:"column:Exit_Date__c" json:"Exit_Date__c"`
	_rescued_data                           string       `gorm:"column:_rescued_data" json:"_rescued_data"`
	ChangeEventHeader                       sql.RawBytes `gorm:"column:ChangeEventHeader" json:"ChangeEventHeader"`
	file_path                               string       `gorm:"column:file_path" json:"file_path"`
	file_size                               int64        `gorm:"column:file_size" json:"file_size"`
	file_modification_time                  time.Time    `gorm:"column:file_modification_time" json:"file_modification_time"`
	file_name                               string       `gorm:"column:file_name" json:"file_name"`
}

// TableName SfCadenceDetails's table name
func (*SfCadenceDetails) TableName() string {
	return TableNameSfCadenceDetails
}
