// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSfCadenceDetail = "sf_cadence_details"

// SfCadenceDetail mapped from table <sf_cadence_details>
type SfCadenceDetail struct {
	ID       string `gorm:"column:Id" json:"Id"`
	AccountC string `gorm:"column:Account__c" json:"Account__c"`
	ActiveC  bool   `gorm:"column:Active__c" json:"Active__c"`
}

func (m SfCadenceDetail) GetId() string {
	return m.ID
}

// TableName SfCadenceDetail's table name
func (*SfCadenceDetail) TableName() string {
	return TableNameSfCadenceDetail
}
