// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/stc-ds-databricks-go/orm/model"
)

func newSfAccount(db *gorm.DB, opts ...gen.DOOption) sfAccount {
	_sfAccount := sfAccount{}

	_sfAccount.sfAccountDo.UseDB(db, opts...)
	_sfAccount.sfAccountDo.UseModel(&model.SfAccount{})

	tableName := _sfAccount.sfAccountDo.TableName()
	_sfAccount.ALL = field.NewAsterisk(tableName)
	_sfAccount.ChangeEventHeader = field.NewField(tableName, "ChangeEventHeader")
	_sfAccount.Name = field.NewString(tableName, "Name")
	_sfAccount.Type = field.NewString(tableName, "Type")
	_sfAccount.RecordTypeId = field.NewString(tableName, "RecordTypeId")
	_sfAccount.ParentId = field.NewString(tableName, "ParentId")
	_sfAccount.Phone = field.NewString(tableName, "Phone")
	_sfAccount.Fax = field.NewString(tableName, "Fax")
	_sfAccount.AccountNumber = field.NewString(tableName, "AccountNumber")
	_sfAccount.Website = field.NewString(tableName, "Website")
	_sfAccount.Sic = field.NewString(tableName, "Sic")
	_sfAccount.Industry = field.NewString(tableName, "Industry")
	_sfAccount.AnnualRevenue = field.NewFloat64(tableName, "AnnualRevenue")
	_sfAccount.NumberOfEmployees = field.NewInt32(tableName, "NumberOfEmployees")
	_sfAccount.Ownership = field.NewString(tableName, "Ownership")
	_sfAccount.TickerSymbol = field.NewString(tableName, "TickerSymbol")
	_sfAccount.Description = field.NewString(tableName, "Description")
	_sfAccount.Rating = field.NewString(tableName, "Rating")
	_sfAccount.Site = field.NewString(tableName, "Site")
	_sfAccount.OwnerId = field.NewString(tableName, "OwnerId")
	_sfAccount.CreatedDate = field.NewTime(tableName, "CreatedDate")
	_sfAccount.CreatedById = field.NewString(tableName, "CreatedById")
	_sfAccount.LastModifiedDate = field.NewTime(tableName, "LastModifiedDate")
	_sfAccount.LastModifiedById = field.NewString(tableName, "LastModifiedById")
	_sfAccount.SourceSystemIdentifier = field.NewString(tableName, "SourceSystemIdentifier")
	_sfAccount.Jigsaw = field.NewString(tableName, "Jigsaw")
	_sfAccount.JigsawCompanyId = field.NewString(tableName, "JigsawCompanyId")
	_sfAccount.AccountSource = field.NewString(tableName, "AccountSource")
	_sfAccount.SicDesc = field.NewString(tableName, "SicDesc")
	_sfAccount.OperatingHoursId = field.NewString(tableName, "OperatingHoursId")
	_sfAccount.IsPriorityRecord = field.NewBool(tableName, "IsPriorityRecord")
	_sfAccount.RTSF_Dormant_Reason__c = field.NewString(tableName, "RTSF_Dormant_Reason__c")
	_sfAccount.Account_Legal_Name__c = field.NewString(tableName, "Account_Legal_Name__c")
	_sfAccount.Carrier_Type__c = field.NewString(tableName, "Carrier_Type__c")
	_sfAccount.Number_Of_Trucks__c = field.NewFloat64(tableName, "Number_Of_Trucks__c")
	_sfAccount.DOT_Number__c = field.NewString(tableName, "DOT_Number__c")
	_sfAccount.MC_Number__c = field.NewString(tableName, "MC_Number__c")
	_sfAccount.RTSF_Not_Eligible_Reason__c = field.NewString(tableName, "RTSF_Not_Eligible_Reason__c")
	_sfAccount.Lead_Source__c = field.NewString(tableName, "Lead_Source__c")
	_sfAccount.Primary_Contact__c = field.NewString(tableName, "Primary_Contact__c")
	_sfAccount.RTSF_Active_Customer__c = field.NewBool(tableName, "RTSF_Active_Customer__c")
	_sfAccount.RTSI_Active_Customer__c = field.NewBool(tableName, "RTSI_Active_Customer__c")
	_sfAccount.OOIDA_Member_ID__c = field.NewString(tableName, "OOIDA_Member_ID__c")
	_sfAccount.Region__c = field.NewString(tableName, "Region__c")
	_sfAccount.RTSIN_Not_Eligible_Reason__c = field.NewString(tableName, "RTSIN_Not_Eligible_Reason__c")
	_sfAccount.Outstanding_Pilot_Balance__c = field.NewFloat64(tableName, "Outstanding_Pilot_Balance__c")
	_sfAccount.CRM_Account_Number__c = field.NewString(tableName, "CRM_Account_Number__c")
	_sfAccount.ProTransport_Cancellation_Reason__c = field.NewString(tableName, "ProTransport_Cancellation_Reason__c")
	_sfAccount.ProTransport_Billing_On_Hold_Date__c = field.NewTime(tableName, "ProTransport_Billing_On_Hold_Date__c")
	_sfAccount.Language__c = field.NewString(tableName, "Language__c")
	_sfAccount.maps__AssignmentRule__c = field.NewString(tableName, "maps__AssignmentRule__c")
	_sfAccount.phone2__c = field.NewString(tableName, "phone2__c")
	_sfAccount.RTSRT_Rep__c = field.NewString(tableName, "RTSRT_Rep__c")
	_sfAccount.RTSF_Ops_Account_Rep__c = field.NewString(tableName, "RTSF_Ops_Account_Rep__c")
	_sfAccount.SBQQ__AssetQuantitiesCombined__c = field.NewBool(tableName, "SBQQ__AssetQuantitiesCombined__c")
	_sfAccount.SBQQ__CoTermedContractsCombined__c = field.NewBool(tableName, "SBQQ__CoTermedContractsCombined__c")
	_sfAccount.SBQQ__CoTerminationEvent__c = field.NewString(tableName, "SBQQ__CoTerminationEvent__c")
	_sfAccount.SBQQ__ContractCoTermination__c = field.NewString(tableName, "SBQQ__ContractCoTermination__c")
	_sfAccount.SBQQ__DefaultOpportunity__c = field.NewString(tableName, "SBQQ__DefaultOpportunity__c")
	_sfAccount.SBQQ__IgnoreParentContractedPrices__c = field.NewBool(tableName, "SBQQ__IgnoreParentContractedPrices__c")
	_sfAccount.SBQQ__PreserveBundle__c = field.NewBool(tableName, "SBQQ__PreserveBundle__c")
	_sfAccount.SBQQ__PriceHoldEnd__c = field.NewTime(tableName, "SBQQ__PriceHoldEnd__c")
	_sfAccount.SBQQ__RenewalModel__c = field.NewString(tableName, "SBQQ__RenewalModel__c")
	_sfAccount.SBQQ__RenewalPricingMethod__c = field.NewString(tableName, "SBQQ__RenewalPricingMethod__c")
	_sfAccount.SBQQ__TaxExempt__c = field.NewString(tableName, "SBQQ__TaxExempt__c")
	_sfAccount.Account_Record_Type__c = field.NewString(tableName, "Account_Record_Type__c")
	_sfAccount.Number_of_Fuel_Cards__c = field.NewFloat64(tableName, "Number_of_Fuel_Cards__c")
	_sfAccount.Has_FLT1__c = field.NewFloat64(tableName, "Has_FLT1__c")
	_sfAccount.RTSIN_Customer_Status__c = field.NewString(tableName, "RTSIN_Customer_Status__c")
	_sfAccount.RTSCS_Rep__c = field.NewString(tableName, "RTSCS_Rep__c")
	_sfAccount.RTSF_Rep__c = field.NewString(tableName, "RTSF_Rep__c")
	_sfAccount.RTSI_Rep__c = field.NewString(tableName, "RTSI_Rep__c")
	_sfAccount.RTS_Software_Rep__c = field.NewString(tableName, "RTS_Software_Rep__c")
	_sfAccount.McLeod_Data__c = field.NewString(tableName, "McLeod_Data__c")
	_sfAccount.Entity_Type__c = field.NewString(tableName, "Entity_Type__c")
	_sfAccount.ProTransport_Account_Number__c = field.NewFloat64(tableName, "ProTransport_Account_Number__c")
	_sfAccount.RTSCS_Dormant_Reason__c = field.NewString(tableName, "RTSCS_Dormant_Reason__c")
	_sfAccount.Active_Fuel_Cards__c = field.NewFloat64(tableName, "Active_Fuel_Cards__c")
	_sfAccount.CloudingoAgent__BAR__c = field.NewString(tableName, "CloudingoAgent__BAR__c")
	_sfAccount.CloudingoAgent__BAS__c = field.NewFloat64(tableName, "CloudingoAgent__BAS__c")
	_sfAccount.ProTransport_Support__c = field.NewString(tableName, "ProTransport_Support__c")
	_sfAccount.ProTransport_Version__c = field.NewString(tableName, "ProTransport_Version__c")
	_sfAccount.RTS_Upload_Integration__c = field.NewString(tableName, "RTS_Upload_Integration__c")
	_sfAccount.Using_EDI__c = field.NewString(tableName, "Using_EDI__c")
	_sfAccount.Software__c = field.NewString(tableName, "Software__c")
	_sfAccount.Hosted__c = field.NewString(tableName, "Hosted__c")
	_sfAccount.RTSCS_On_Hold__c = field.NewBool(tableName, "RTSCS_On_Hold__c")
	_sfAccount.Trip_Management_Start_Date__c = field.NewTime(tableName, "Trip_Management_Start_Date__c")
	_sfAccount.Trip_Management__c = field.NewString(tableName, "Trip_Management__c")
	_sfAccount.Citrix_User__c = field.NewString(tableName, "Citrix_User__c")
	_sfAccount.CAB_ISS_Score__c = field.NewFloat64(tableName, "CAB_ISS_Score__c")
	_sfAccount.US_Veteran__c = field.NewBool(tableName, "US_Veteran__c")
	_sfAccount.CloudingoAgent__BAV__c = field.NewString(tableName, "CloudingoAgent__BAV__c")
	_sfAccount.CloudingoAgent__BRDI__c = field.NewString(tableName, "CloudingoAgent__BRDI__c")
	_sfAccount.CloudingoAgent__BTZ__c = field.NewString(tableName, "CloudingoAgent__BTZ__c")
	_sfAccount.CloudingoAgent__SAR__c = field.NewString(tableName, "CloudingoAgent__SAR__c")
	_sfAccount.CloudingoAgent__SAS__c = field.NewFloat64(tableName, "CloudingoAgent__SAS__c")
	_sfAccount.CloudingoAgent__SAV__c = field.NewString(tableName, "CloudingoAgent__SAV__c")
	_sfAccount.CloudingoAgent__SRDI__c = field.NewString(tableName, "CloudingoAgent__SRDI__c")
	_sfAccount.CloudingoAgent__STZ__c = field.NewString(tableName, "CloudingoAgent__STZ__c")
	_sfAccount.Cancellation_Date__c = field.NewTime(tableName, "Cancellation_Date__c")
	_sfAccount.First_Fuel_Date__c = field.NewTime(tableName, "First_Fuel_Date__c")
	_sfAccount.LM_PFJ_Gals__c = field.NewFloat64(tableName, "LM_PFJ_Gals__c")
	_sfAccount.LM_RTS_Plus_Gals__c = field.NewFloat64(tableName, "LM_RTS_Plus_Gals__c")
	_sfAccount.LM_Total_Gals__c = field.NewFloat64(tableName, "LM_Total_Gals__c")
	_sfAccount.LM_of_Transactions__c = field.NewFloat64(tableName, "LM_of_Transactions__c")
	_sfAccount.Last_Fuel_Date__c = field.NewTime(tableName, "Last_Fuel_Date__c")
	_sfAccount.MTD_PFJ_Gals__c = field.NewFloat64(tableName, "MTD_PFJ_Gals__c")
	_sfAccount.MTD_RTS_Plus_Gals__c = field.NewFloat64(tableName, "MTD_RTS_Plus_Gals__c")
	_sfAccount.MTD_Total_Gals__c = field.NewFloat64(tableName, "MTD_Total_Gals__c")
	_sfAccount.MTD_of_Transactions__c = field.NewFloat64(tableName, "MTD_of_Transactions__c")
	_sfAccount.YTD_PFJ_Gals__c = field.NewFloat64(tableName, "YTD_PFJ_Gals__c")
	_sfAccount.YTD_RTS_Plus_Gals__c = field.NewFloat64(tableName, "YTD_RTS_Plus_Gals__c")
	_sfAccount.YTD_Total_Gals__c = field.NewFloat64(tableName, "YTD_Total_Gals__c")
	_sfAccount.YTD_of_Transactions__c = field.NewFloat64(tableName, "YTD_of_Transactions__c")
	_sfAccount.Implementation_Tier__c = field.NewString(tableName, "Implementation_Tier__c")
	_sfAccount.Primary_Contact_Email__c = field.NewString(tableName, "Primary_Contact_Email__c")
	_sfAccount.Primary_Contact_Phone__c = field.NewString(tableName, "Primary_Contact_Phone__c")
	_sfAccount.MX_Number__c = field.NewString(tableName, "MX_Number__c")
	_sfAccount.IFTA_Customer__c = field.NewBool(tableName, "IFTA_Customer__c")
	_sfAccount.Alert_Tracking_Status__c = field.NewString(tableName, "Alert_Tracking_Status__c")
	_sfAccount.RTSPT_WEB_Active_Customer__c = field.NewBool(tableName, "RTSPT_WEB_Active_Customer__c")
	_sfAccount.RTSCS_Customer_Status__c = field.NewString(tableName, "RTSCS_Customer_Status__c")
	_sfAccount.Alert_Date__c = field.NewTime(tableName, "Alert_Date__c")
	_sfAccount.Alert_Type__c = field.NewString(tableName, "Alert_Type__c")
	_sfAccount.PFJ_Ascend_Number__c = field.NewString(tableName, "PFJ_Ascend_Number__c")
	_sfAccount.PFJ_Current_Wallet_Share__c = field.NewString(tableName, "PFJ_Current_Wallet_Share__c")
	_sfAccount.PFJ_Customer_Status__c = field.NewString(tableName, "PFJ_Customer_Status__c")
	_sfAccount.PFJ_Factoring_Competitor__c = field.NewString(tableName, "PFJ_Factoring_Competitor__c")
	_sfAccount.STC_Transaction_Id__c = field.NewString(tableName, "STC_Transaction_Id__c")
	_sfAccount.PFJ_Gallon_Alert__c = field.NewString(tableName, "PFJ_Gallon_Alert__c")
	_sfAccount.PFJ_Gallon_Potential__c = field.NewString(tableName, "PFJ_Gallon_Potential__c")
	_sfAccount.PFJ_Last_Month_Gallons__c = field.NewFloat64(tableName, "PFJ_Last_Month_Gallons__c")
	_sfAccount.PFJ_Last_Update_Date_of_Fuel_History__c = field.NewString(tableName, "PFJ_Last_Update_Date_of_Fuel_History__c")
	_sfAccount.PFJ_Last_Week_Gallons__c = field.NewFloat64(tableName, "PFJ_Last_Week_Gallons__c")
	_sfAccount.PFJ_Min_Gallon_Amount__c = field.NewFloat64(tableName, "PFJ_Min_Gallon_Amount__c")
	_sfAccount.PFJ_Min_Gallon_Percentage__c = field.NewFloat64(tableName, "PFJ_Min_Gallon_Percentage__c")
	_sfAccount.PFJ_Number_of_Co_Trucks__c = field.NewFloat64(tableName, "PFJ_Number_of_Co_Trucks__c")
	_sfAccount.PFJ_Number_of_Op_Trucks__c = field.NewFloat64(tableName, "PFJ_Number_of_Op_Trucks__c")
	_sfAccount.PFJ_Number_of_Trucks__c = field.NewFloat64(tableName, "PFJ_Number_of_Trucks__c")
	_sfAccount.PFJ_RTS_Eligible__c = field.NewString(tableName, "PFJ_RTS_Eligible__c")
	_sfAccount.PFJ_RTS_Factoring_Notes__c = field.NewString(tableName, "PFJ_RTS_Factoring_Notes__c")
	_sfAccount.PFJ_Rep_Email__c = field.NewString(tableName, "PFJ_Rep_Email__c")
	_sfAccount.PFJ_Rep_Name__c = field.NewString(tableName, "PFJ_Rep_Name__c")
	_sfAccount.PFJ_Rep_Phone__c = field.NewString(tableName, "PFJ_Rep_Phone__c")
	_sfAccount.PFJ_Status__c = field.NewString(tableName, "PFJ_Status__c")
	_sfAccount.PFJ_YTD_Gallons__c = field.NewFloat64(tableName, "PFJ_YTD_Gallons__c")
	_sfAccount.Partner_Entity_ID__c = field.NewString(tableName, "Partner_Entity_ID__c")
	_sfAccount.RTS_PFJ_Factoring_Notes__c = field.NewString(tableName, "RTS_PFJ_Factoring_Notes__c")
	_sfAccount.RTSCS_Account_Manager__c = field.NewString(tableName, "RTSCS_Account_Manager__c")
	_sfAccount.UCC_Filed_By__c = field.NewString(tableName, "UCC_Filed_By__c")
	_sfAccount.PFJ_Factoring_Competitor_Rate__c = field.NewFloat64(tableName, "PFJ_Factoring_Competitor_Rate__c")
	_sfAccount.LM_Cards_Used__c = field.NewFloat64(tableName, "LM_Cards_Used__c")
	_sfAccount.MTD_Cards_Used__c = field.NewFloat64(tableName, "MTD_Cards_Used__c")
	_sfAccount.YTD_Cards_Used__c = field.NewFloat64(tableName, "YTD_Cards_Used__c")
	_sfAccount.FMCSA_Truck_Count__c = field.NewFloat64(tableName, "FMCSA_Truck_Count__c")
	_sfAccount.Deal_Age_at_Alert__c = field.NewFloat64(tableName, "Deal_Age_at_Alert__c")
	_sfAccount.Prior_30_Day_Volume__c = field.NewFloat64(tableName, "Prior_30_Day_Volume__c")
	_sfAccount.Cadence_Active__c = field.NewBool(tableName, "Cadence_Active__c")
	_sfAccount.Cadence_Balance__c = field.NewFloat64(tableName, "Cadence_Balance__c")
	_sfAccount.Cadence_First_Funding_Date__c = field.NewTime(tableName, "Cadence_First_Funding_Date__c")
	_sfAccount.Cadence_Fuel_Card_Group_Code__c = field.NewString(tableName, "Cadence_Fuel_Card_Group_Code__c")
	_sfAccount.Cadence_Fuel_Status_Group_Code__c = field.NewString(tableName, "Cadence_Fuel_Status_Group_Code__c")
	_sfAccount.Cadence_Last_Funding_Date__c = field.NewTime(tableName, "Cadence_Last_Funding_Date__c")
	_sfAccount.Master_Factorsoft_Client_Number__c = field.NewString(tableName, "Master_Factorsoft_Client_Number__c")
	_sfAccount.Pilot_Travel_Centers_LLC_Broker_Code__c = field.NewBool(tableName, "Pilot_Travel_Centers_LLC_Broker_Code__c")
	_sfAccount.Software_Tier__c = field.NewString(tableName, "Software_Tier__c")
	_sfAccount.UCC_Continued_Date__c = field.NewTime(tableName, "UCC_Continued_Date__c")
	_sfAccount.Bundle_Status__c = field.NewString(tableName, "Bundle_Status__c")
	_sfAccount.Compliance_Status__c = field.NewString(tableName, "Compliance_Status__c")
	_sfAccount.MRA_Exception__c = field.NewString(tableName, "MRA_Exception__c")
	_sfAccount.RTS_Pro_Last_Use__c = field.NewTime(tableName, "RTS_Pro_Last_Use__c")
	_sfAccount.RTSF_Customer_Status__c = field.NewString(tableName, "RTSF_Customer_Status__c")
	_sfAccount.RTSI_Customer_Status__c = field.NewString(tableName, "RTSI_Customer_Status__c")
	_sfAccount.RTSPT_Customer_Status__c = field.NewString(tableName, "RTSPT_Customer_Status__c")
	_sfAccount.RTSRT_Customer_Status__c = field.NewString(tableName, "RTSRT_Customer_Status__c")
	_sfAccount.Truckers_Solution__c = field.NewBool(tableName, "Truckers_Solution__c")
	_sfAccount.Authority_Status__c = field.NewString(tableName, "Authority_Status__c")
	_sfAccount.RTSCS_Not_Eligible_Reason__c = field.NewString(tableName, "RTSCS_Not_Eligible_Reason__c")
	_sfAccount.Bundle_Cards_Used_LM__c = field.NewFloat64(tableName, "Bundle_Cards_Used_LM__c")
	_sfAccount.Bundle_Compliance__c = field.NewFloat64(tableName, "Bundle_Compliance__c")
	_sfAccount.Bundle_Expected_LM_Gals__c = field.NewString(tableName, "Bundle_Expected_LM_Gals__c")
	_sfAccount.Bundle_Grace_Period_End_Date__c = field.NewTime(tableName, "Bundle_Grace_Period_End_Date__c")
	_sfAccount.Bundle_LM_Gallons__c = field.NewFloat64(tableName, "Bundle_LM_Gallons__c")
	_sfAccount.MRA_LM_Volume__c = field.NewFloat64(tableName, "MRA_LM_Volume__c")
	_sfAccount.ReplayId = field.NewString(tableName, "ReplayId")
	_sfAccount.EntityName = field.NewString(tableName, "EntityName")
	_sfAccount.Id = field.NewString(tableName, "Id")
	_sfAccount.year = field.NewInt32(tableName, "year")
	_sfAccount.month = field.NewInt32(tableName, "month")
	_sfAccount.day = field.NewInt32(tableName, "day")
	_sfAccount.hour = field.NewInt32(tableName, "hour")
	_sfAccount._rescued_data = field.NewString(tableName, "_rescued_data")
	_sfAccount.IsDeleted = field.NewBool(tableName, "IsDeleted")
	_sfAccount.MasterRecordId = field.NewString(tableName, "MasterRecordId")
	_sfAccount.PhotoUrl = field.NewString(tableName, "PhotoUrl")
	_sfAccount.SystemModstamp = field.NewTime(tableName, "SystemModstamp")
	_sfAccount.LastActivityDate = field.NewTime(tableName, "LastActivityDate")
	_sfAccount.LastViewedDate = field.NewString(tableName, "LastViewedDate")
	_sfAccount.LastReferencedDate = field.NewString(tableName, "LastReferencedDate")
	_sfAccount.IsPartner = field.NewBool(tableName, "IsPartner")
	_sfAccount.ChannelProgramName = field.NewString(tableName, "ChannelProgramName")
	_sfAccount.ChannelProgramLevelName = field.NewString(tableName, "ChannelProgramLevelName")
	_sfAccount.PersonActionCadenceId = field.NewString(tableName, "PersonActionCadenceId")
	_sfAccount.PersonActionCadenceAssigneeId = field.NewString(tableName, "PersonActionCadenceAssigneeId")
	_sfAccount.PersonActionCadenceState = field.NewString(tableName, "PersonActionCadenceState")
	_sfAccount.PersonScheduledResumeDateTime = field.NewString(tableName, "PersonScheduledResumeDateTime")
	_sfAccount.ActivityMetricId = field.NewString(tableName, "ActivityMetricId")
	_sfAccount.RTSCS_Active_Customer__c = field.NewBool(tableName, "RTSCS_Active_Customer__c")
	_sfAccount.RTSPT_Active_Customer__c = field.NewBool(tableName, "RTSPT_Active_Customer__c")
	_sfAccount.FLT1_Gallon_Report__c = field.NewString(tableName, "FLT1_Gallon_Report__c")
	_sfAccount.Partner_Gallon_Report__c = field.NewString(tableName, "Partner_Gallon_Report__c")
	_sfAccount.Last_Activity_Date__c = field.NewTime(tableName, "Last_Activity_Date__c")
	_sfAccount.LM_Partner_Gals__c = field.NewFloat64(tableName, "LM_Partner_Gals__c")
	_sfAccount.MTD_Partner_Gals__c = field.NewFloat64(tableName, "MTD_Partner_Gals__c")
	_sfAccount.YTD_Partner_Gals__c = field.NewFloat64(tableName, "YTD_Partner_Gals__c")
	_sfAccount.RTSEF_Customer_Status__c = field.NewString(tableName, "RTSEF_Customer_Status__c")
	_sfAccount.RTSEF_Not_Eligible_Reason__c = field.NewString(tableName, "RTSEF_Not_Eligible_Reason__c")
	_sfAccount.BillingStreet = field.NewString(tableName, "BillingStreet")
	_sfAccount.BillingCity = field.NewString(tableName, "BillingCity")
	_sfAccount.BillingState = field.NewString(tableName, "BillingState")
	_sfAccount.BillingPostalCode = field.NewString(tableName, "BillingPostalCode")
	_sfAccount.BillingCountry = field.NewString(tableName, "BillingCountry")
	_sfAccount.BillingStateCode = field.NewString(tableName, "BillingStateCode")
	_sfAccount.BillingCountryCode = field.NewString(tableName, "BillingCountryCode")
	_sfAccount.BillingLatitude = field.NewFloat64(tableName, "BillingLatitude")
	_sfAccount.BillingLongitude = field.NewFloat64(tableName, "BillingLongitude")
	_sfAccount.BillingGeocodeAccuracy = field.NewString(tableName, "BillingGeocodeAccuracy")
	_sfAccount.ShippingStreet = field.NewString(tableName, "ShippingStreet")
	_sfAccount.ShippingCity = field.NewString(tableName, "ShippingCity")
	_sfAccount.ShippingState = field.NewString(tableName, "ShippingState")
	_sfAccount.ShippingPostalCode = field.NewString(tableName, "ShippingPostalCode")
	_sfAccount.ShippingCountry = field.NewString(tableName, "ShippingCountry")
	_sfAccount.ShippingStateCode = field.NewString(tableName, "ShippingStateCode")
	_sfAccount.ShippingCountryCode = field.NewString(tableName, "ShippingCountryCode")
	_sfAccount.ShippingLatitude = field.NewFloat64(tableName, "ShippingLatitude")
	_sfAccount.ShippingLongitude = field.NewFloat64(tableName, "ShippingLongitude")
	_sfAccount.ShippingGeocodeAccuracy = field.NewString(tableName, "ShippingGeocodeAccuracy")

	_sfAccount.fillFieldMap()

	return _sfAccount
}

type sfAccount struct {
	sfAccountDo

	ALL                                     field.Asterisk
	ChangeEventHeader                       field.Field
	Name                                    field.String
	Type                                    field.String
	RecordTypeId                            field.String
	ParentId                                field.String
	Phone                                   field.String
	Fax                                     field.String
	AccountNumber                           field.String
	Website                                 field.String
	Sic                                     field.String
	Industry                                field.String
	AnnualRevenue                           field.Float64
	NumberOfEmployees                       field.Int32
	Ownership                               field.String
	TickerSymbol                            field.String
	Description                             field.String
	Rating                                  field.String
	Site                                    field.String
	OwnerId                                 field.String
	CreatedDate                             field.Time
	CreatedById                             field.String
	LastModifiedDate                        field.Time
	LastModifiedById                        field.String
	SourceSystemIdentifier                  field.String
	Jigsaw                                  field.String
	JigsawCompanyId                         field.String
	AccountSource                           field.String
	SicDesc                                 field.String
	OperatingHoursId                        field.String
	IsPriorityRecord                        field.Bool
	RTSF_Dormant_Reason__c                  field.String
	Account_Legal_Name__c                   field.String
	Carrier_Type__c                         field.String
	Number_Of_Trucks__c                     field.Float64
	DOT_Number__c                           field.String
	MC_Number__c                            field.String
	RTSF_Not_Eligible_Reason__c             field.String
	Lead_Source__c                          field.String
	Primary_Contact__c                      field.String
	RTSF_Active_Customer__c                 field.Bool
	RTSI_Active_Customer__c                 field.Bool
	OOIDA_Member_ID__c                      field.String
	Region__c                               field.String
	RTSIN_Not_Eligible_Reason__c            field.String
	Outstanding_Pilot_Balance__c            field.Float64
	CRM_Account_Number__c                   field.String
	ProTransport_Cancellation_Reason__c     field.String
	ProTransport_Billing_On_Hold_Date__c    field.Time
	Language__c                             field.String
	maps__AssignmentRule__c                 field.String
	phone2__c                               field.String
	RTSRT_Rep__c                            field.String
	RTSF_Ops_Account_Rep__c                 field.String
	SBQQ__AssetQuantitiesCombined__c        field.Bool
	SBQQ__CoTermedContractsCombined__c      field.Bool
	SBQQ__CoTerminationEvent__c             field.String
	SBQQ__ContractCoTermination__c          field.String
	SBQQ__DefaultOpportunity__c             field.String
	SBQQ__IgnoreParentContractedPrices__c   field.Bool
	SBQQ__PreserveBundle__c                 field.Bool
	SBQQ__PriceHoldEnd__c                   field.Time
	SBQQ__RenewalModel__c                   field.String
	SBQQ__RenewalPricingMethod__c           field.String
	SBQQ__TaxExempt__c                      field.String
	Account_Record_Type__c                  field.String
	Number_of_Fuel_Cards__c                 field.Float64
	Has_FLT1__c                             field.Float64
	RTSIN_Customer_Status__c                field.String
	RTSCS_Rep__c                            field.String
	RTSF_Rep__c                             field.String
	RTSI_Rep__c                             field.String
	RTS_Software_Rep__c                     field.String
	McLeod_Data__c                          field.String
	Entity_Type__c                          field.String
	ProTransport_Account_Number__c          field.Float64
	RTSCS_Dormant_Reason__c                 field.String
	Active_Fuel_Cards__c                    field.Float64
	CloudingoAgent__BAR__c                  field.String
	CloudingoAgent__BAS__c                  field.Float64
	ProTransport_Support__c                 field.String
	ProTransport_Version__c                 field.String
	RTS_Upload_Integration__c               field.String
	Using_EDI__c                            field.String
	Software__c                             field.String
	Hosted__c                               field.String
	RTSCS_On_Hold__c                        field.Bool
	Trip_Management_Start_Date__c           field.Time
	Trip_Management__c                      field.String
	Citrix_User__c                          field.String
	CAB_ISS_Score__c                        field.Float64
	US_Veteran__c                           field.Bool
	CloudingoAgent__BAV__c                  field.String
	CloudingoAgent__BRDI__c                 field.String
	CloudingoAgent__BTZ__c                  field.String
	CloudingoAgent__SAR__c                  field.String
	CloudingoAgent__SAS__c                  field.Float64
	CloudingoAgent__SAV__c                  field.String
	CloudingoAgent__SRDI__c                 field.String
	CloudingoAgent__STZ__c                  field.String
	Cancellation_Date__c                    field.Time
	First_Fuel_Date__c                      field.Time
	LM_PFJ_Gals__c                          field.Float64
	LM_RTS_Plus_Gals__c                     field.Float64
	LM_Total_Gals__c                        field.Float64
	LM_of_Transactions__c                   field.Float64
	Last_Fuel_Date__c                       field.Time
	MTD_PFJ_Gals__c                         field.Float64
	MTD_RTS_Plus_Gals__c                    field.Float64
	MTD_Total_Gals__c                       field.Float64
	MTD_of_Transactions__c                  field.Float64
	YTD_PFJ_Gals__c                         field.Float64
	YTD_RTS_Plus_Gals__c                    field.Float64
	YTD_Total_Gals__c                       field.Float64
	YTD_of_Transactions__c                  field.Float64
	Implementation_Tier__c                  field.String
	Primary_Contact_Email__c                field.String
	Primary_Contact_Phone__c                field.String
	MX_Number__c                            field.String
	IFTA_Customer__c                        field.Bool
	Alert_Tracking_Status__c                field.String
	RTSPT_WEB_Active_Customer__c            field.Bool
	RTSCS_Customer_Status__c                field.String
	Alert_Date__c                           field.Time
	Alert_Type__c                           field.String
	PFJ_Ascend_Number__c                    field.String
	PFJ_Current_Wallet_Share__c             field.String
	PFJ_Customer_Status__c                  field.String
	PFJ_Factoring_Competitor__c             field.String
	STC_Transaction_Id__c                   field.String
	PFJ_Gallon_Alert__c                     field.String
	PFJ_Gallon_Potential__c                 field.String
	PFJ_Last_Month_Gallons__c               field.Float64
	PFJ_Last_Update_Date_of_Fuel_History__c field.String
	PFJ_Last_Week_Gallons__c                field.Float64
	PFJ_Min_Gallon_Amount__c                field.Float64
	PFJ_Min_Gallon_Percentage__c            field.Float64
	PFJ_Number_of_Co_Trucks__c              field.Float64
	PFJ_Number_of_Op_Trucks__c              field.Float64
	PFJ_Number_of_Trucks__c                 field.Float64
	PFJ_RTS_Eligible__c                     field.String
	PFJ_RTS_Factoring_Notes__c              field.String
	PFJ_Rep_Email__c                        field.String
	PFJ_Rep_Name__c                         field.String
	PFJ_Rep_Phone__c                        field.String
	PFJ_Status__c                           field.String
	PFJ_YTD_Gallons__c                      field.Float64
	Partner_Entity_ID__c                    field.String
	RTS_PFJ_Factoring_Notes__c              field.String
	RTSCS_Account_Manager__c                field.String
	UCC_Filed_By__c                         field.String
	PFJ_Factoring_Competitor_Rate__c        field.Float64
	LM_Cards_Used__c                        field.Float64
	MTD_Cards_Used__c                       field.Float64
	YTD_Cards_Used__c                       field.Float64
	FMCSA_Truck_Count__c                    field.Float64
	Deal_Age_at_Alert__c                    field.Float64
	Prior_30_Day_Volume__c                  field.Float64
	Cadence_Active__c                       field.Bool
	Cadence_Balance__c                      field.Float64
	Cadence_First_Funding_Date__c           field.Time
	Cadence_Fuel_Card_Group_Code__c         field.String
	Cadence_Fuel_Status_Group_Code__c       field.String
	Cadence_Last_Funding_Date__c            field.Time
	Master_Factorsoft_Client_Number__c      field.String
	Pilot_Travel_Centers_LLC_Broker_Code__c field.Bool
	Software_Tier__c                        field.String
	UCC_Continued_Date__c                   field.Time
	Bundle_Status__c                        field.String
	Compliance_Status__c                    field.String
	MRA_Exception__c                        field.String
	RTS_Pro_Last_Use__c                     field.Time
	RTSF_Customer_Status__c                 field.String
	RTSI_Customer_Status__c                 field.String
	RTSPT_Customer_Status__c                field.String
	RTSRT_Customer_Status__c                field.String
	Truckers_Solution__c                    field.Bool
	Authority_Status__c                     field.String
	RTSCS_Not_Eligible_Reason__c            field.String
	Bundle_Cards_Used_LM__c                 field.Float64
	Bundle_Compliance__c                    field.Float64
	Bundle_Expected_LM_Gals__c              field.String
	Bundle_Grace_Period_End_Date__c         field.Time
	Bundle_LM_Gallons__c                    field.Float64
	MRA_LM_Volume__c                        field.Float64
	ReplayId                                field.String
	EntityName                              field.String
	Id                                      field.String
	year                                    field.Int32
	month                                   field.Int32
	day                                     field.Int32
	hour                                    field.Int32
	_rescued_data                           field.String
	IsDeleted                               field.Bool
	MasterRecordId                          field.String
	PhotoUrl                                field.String
	SystemModstamp                          field.Time
	LastActivityDate                        field.Time
	LastViewedDate                          field.String
	LastReferencedDate                      field.String
	IsPartner                               field.Bool
	ChannelProgramName                      field.String
	ChannelProgramLevelName                 field.String
	PersonActionCadenceId                   field.String
	PersonActionCadenceAssigneeId           field.String
	PersonActionCadenceState                field.String
	PersonScheduledResumeDateTime           field.String
	ActivityMetricId                        field.String
	RTSCS_Active_Customer__c                field.Bool
	RTSPT_Active_Customer__c                field.Bool
	FLT1_Gallon_Report__c                   field.String
	Partner_Gallon_Report__c                field.String
	Last_Activity_Date__c                   field.Time
	LM_Partner_Gals__c                      field.Float64
	MTD_Partner_Gals__c                     field.Float64
	YTD_Partner_Gals__c                     field.Float64
	RTSEF_Customer_Status__c                field.String
	RTSEF_Not_Eligible_Reason__c            field.String
	BillingStreet                           field.String
	BillingCity                             field.String
	BillingState                            field.String
	BillingPostalCode                       field.String
	BillingCountry                          field.String
	BillingStateCode                        field.String
	BillingCountryCode                      field.String
	BillingLatitude                         field.Float64
	BillingLongitude                        field.Float64
	BillingGeocodeAccuracy                  field.String
	ShippingStreet                          field.String
	ShippingCity                            field.String
	ShippingState                           field.String
	ShippingPostalCode                      field.String
	ShippingCountry                         field.String
	ShippingStateCode                       field.String
	ShippingCountryCode                     field.String
	ShippingLatitude                        field.Float64
	ShippingLongitude                       field.Float64
	ShippingGeocodeAccuracy                 field.String

	fieldMap map[string]field.Expr
}

func (s sfAccount) Table(newTableName string) *sfAccount {
	s.sfAccountDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sfAccount) As(alias string) *sfAccount {
	s.sfAccountDo.DO = *(s.sfAccountDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sfAccount) updateTableName(table string) *sfAccount {
	s.ALL = field.NewAsterisk(table)
	s.ChangeEventHeader = field.NewField(table, "ChangeEventHeader")
	s.Name = field.NewString(table, "Name")
	s.Type = field.NewString(table, "Type")
	s.RecordTypeId = field.NewString(table, "RecordTypeId")
	s.ParentId = field.NewString(table, "ParentId")
	s.Phone = field.NewString(table, "Phone")
	s.Fax = field.NewString(table, "Fax")
	s.AccountNumber = field.NewString(table, "AccountNumber")
	s.Website = field.NewString(table, "Website")
	s.Sic = field.NewString(table, "Sic")
	s.Industry = field.NewString(table, "Industry")
	s.AnnualRevenue = field.NewFloat64(table, "AnnualRevenue")
	s.NumberOfEmployees = field.NewInt32(table, "NumberOfEmployees")
	s.Ownership = field.NewString(table, "Ownership")
	s.TickerSymbol = field.NewString(table, "TickerSymbol")
	s.Description = field.NewString(table, "Description")
	s.Rating = field.NewString(table, "Rating")
	s.Site = field.NewString(table, "Site")
	s.OwnerId = field.NewString(table, "OwnerId")
	s.CreatedDate = field.NewTime(table, "CreatedDate")
	s.CreatedById = field.NewString(table, "CreatedById")
	s.LastModifiedDate = field.NewTime(table, "LastModifiedDate")
	s.LastModifiedById = field.NewString(table, "LastModifiedById")
	s.SourceSystemIdentifier = field.NewString(table, "SourceSystemIdentifier")
	s.Jigsaw = field.NewString(table, "Jigsaw")
	s.JigsawCompanyId = field.NewString(table, "JigsawCompanyId")
	s.AccountSource = field.NewString(table, "AccountSource")
	s.SicDesc = field.NewString(table, "SicDesc")
	s.OperatingHoursId = field.NewString(table, "OperatingHoursId")
	s.IsPriorityRecord = field.NewBool(table, "IsPriorityRecord")
	s.RTSF_Dormant_Reason__c = field.NewString(table, "RTSF_Dormant_Reason__c")
	s.Account_Legal_Name__c = field.NewString(table, "Account_Legal_Name__c")
	s.Carrier_Type__c = field.NewString(table, "Carrier_Type__c")
	s.Number_Of_Trucks__c = field.NewFloat64(table, "Number_Of_Trucks__c")
	s.DOT_Number__c = field.NewString(table, "DOT_Number__c")
	s.MC_Number__c = field.NewString(table, "MC_Number__c")
	s.RTSF_Not_Eligible_Reason__c = field.NewString(table, "RTSF_Not_Eligible_Reason__c")
	s.Lead_Source__c = field.NewString(table, "Lead_Source__c")
	s.Primary_Contact__c = field.NewString(table, "Primary_Contact__c")
	s.RTSF_Active_Customer__c = field.NewBool(table, "RTSF_Active_Customer__c")
	s.RTSI_Active_Customer__c = field.NewBool(table, "RTSI_Active_Customer__c")
	s.OOIDA_Member_ID__c = field.NewString(table, "OOIDA_Member_ID__c")
	s.Region__c = field.NewString(table, "Region__c")
	s.RTSIN_Not_Eligible_Reason__c = field.NewString(table, "RTSIN_Not_Eligible_Reason__c")
	s.Outstanding_Pilot_Balance__c = field.NewFloat64(table, "Outstanding_Pilot_Balance__c")
	s.CRM_Account_Number__c = field.NewString(table, "CRM_Account_Number__c")
	s.ProTransport_Cancellation_Reason__c = field.NewString(table, "ProTransport_Cancellation_Reason__c")
	s.ProTransport_Billing_On_Hold_Date__c = field.NewTime(table, "ProTransport_Billing_On_Hold_Date__c")
	s.Language__c = field.NewString(table, "Language__c")
	s.maps__AssignmentRule__c = field.NewString(table, "maps__AssignmentRule__c")
	s.phone2__c = field.NewString(table, "phone2__c")
	s.RTSRT_Rep__c = field.NewString(table, "RTSRT_Rep__c")
	s.RTSF_Ops_Account_Rep__c = field.NewString(table, "RTSF_Ops_Account_Rep__c")
	s.SBQQ__AssetQuantitiesCombined__c = field.NewBool(table, "SBQQ__AssetQuantitiesCombined__c")
	s.SBQQ__CoTermedContractsCombined__c = field.NewBool(table, "SBQQ__CoTermedContractsCombined__c")
	s.SBQQ__CoTerminationEvent__c = field.NewString(table, "SBQQ__CoTerminationEvent__c")
	s.SBQQ__ContractCoTermination__c = field.NewString(table, "SBQQ__ContractCoTermination__c")
	s.SBQQ__DefaultOpportunity__c = field.NewString(table, "SBQQ__DefaultOpportunity__c")
	s.SBQQ__IgnoreParentContractedPrices__c = field.NewBool(table, "SBQQ__IgnoreParentContractedPrices__c")
	s.SBQQ__PreserveBundle__c = field.NewBool(table, "SBQQ__PreserveBundle__c")
	s.SBQQ__PriceHoldEnd__c = field.NewTime(table, "SBQQ__PriceHoldEnd__c")
	s.SBQQ__RenewalModel__c = field.NewString(table, "SBQQ__RenewalModel__c")
	s.SBQQ__RenewalPricingMethod__c = field.NewString(table, "SBQQ__RenewalPricingMethod__c")
	s.SBQQ__TaxExempt__c = field.NewString(table, "SBQQ__TaxExempt__c")
	s.Account_Record_Type__c = field.NewString(table, "Account_Record_Type__c")
	s.Number_of_Fuel_Cards__c = field.NewFloat64(table, "Number_of_Fuel_Cards__c")
	s.Has_FLT1__c = field.NewFloat64(table, "Has_FLT1__c")
	s.RTSIN_Customer_Status__c = field.NewString(table, "RTSIN_Customer_Status__c")
	s.RTSCS_Rep__c = field.NewString(table, "RTSCS_Rep__c")
	s.RTSF_Rep__c = field.NewString(table, "RTSF_Rep__c")
	s.RTSI_Rep__c = field.NewString(table, "RTSI_Rep__c")
	s.RTS_Software_Rep__c = field.NewString(table, "RTS_Software_Rep__c")
	s.McLeod_Data__c = field.NewString(table, "McLeod_Data__c")
	s.Entity_Type__c = field.NewString(table, "Entity_Type__c")
	s.ProTransport_Account_Number__c = field.NewFloat64(table, "ProTransport_Account_Number__c")
	s.RTSCS_Dormant_Reason__c = field.NewString(table, "RTSCS_Dormant_Reason__c")
	s.Active_Fuel_Cards__c = field.NewFloat64(table, "Active_Fuel_Cards__c")
	s.CloudingoAgent__BAR__c = field.NewString(table, "CloudingoAgent__BAR__c")
	s.CloudingoAgent__BAS__c = field.NewFloat64(table, "CloudingoAgent__BAS__c")
	s.ProTransport_Support__c = field.NewString(table, "ProTransport_Support__c")
	s.ProTransport_Version__c = field.NewString(table, "ProTransport_Version__c")
	s.RTS_Upload_Integration__c = field.NewString(table, "RTS_Upload_Integration__c")
	s.Using_EDI__c = field.NewString(table, "Using_EDI__c")
	s.Software__c = field.NewString(table, "Software__c")
	s.Hosted__c = field.NewString(table, "Hosted__c")
	s.RTSCS_On_Hold__c = field.NewBool(table, "RTSCS_On_Hold__c")
	s.Trip_Management_Start_Date__c = field.NewTime(table, "Trip_Management_Start_Date__c")
	s.Trip_Management__c = field.NewString(table, "Trip_Management__c")
	s.Citrix_User__c = field.NewString(table, "Citrix_User__c")
	s.CAB_ISS_Score__c = field.NewFloat64(table, "CAB_ISS_Score__c")
	s.US_Veteran__c = field.NewBool(table, "US_Veteran__c")
	s.CloudingoAgent__BAV__c = field.NewString(table, "CloudingoAgent__BAV__c")
	s.CloudingoAgent__BRDI__c = field.NewString(table, "CloudingoAgent__BRDI__c")
	s.CloudingoAgent__BTZ__c = field.NewString(table, "CloudingoAgent__BTZ__c")
	s.CloudingoAgent__SAR__c = field.NewString(table, "CloudingoAgent__SAR__c")
	s.CloudingoAgent__SAS__c = field.NewFloat64(table, "CloudingoAgent__SAS__c")
	s.CloudingoAgent__SAV__c = field.NewString(table, "CloudingoAgent__SAV__c")
	s.CloudingoAgent__SRDI__c = field.NewString(table, "CloudingoAgent__SRDI__c")
	s.CloudingoAgent__STZ__c = field.NewString(table, "CloudingoAgent__STZ__c")
	s.Cancellation_Date__c = field.NewTime(table, "Cancellation_Date__c")
	s.First_Fuel_Date__c = field.NewTime(table, "First_Fuel_Date__c")
	s.LM_PFJ_Gals__c = field.NewFloat64(table, "LM_PFJ_Gals__c")
	s.LM_RTS_Plus_Gals__c = field.NewFloat64(table, "LM_RTS_Plus_Gals__c")
	s.LM_Total_Gals__c = field.NewFloat64(table, "LM_Total_Gals__c")
	s.LM_of_Transactions__c = field.NewFloat64(table, "LM_of_Transactions__c")
	s.Last_Fuel_Date__c = field.NewTime(table, "Last_Fuel_Date__c")
	s.MTD_PFJ_Gals__c = field.NewFloat64(table, "MTD_PFJ_Gals__c")
	s.MTD_RTS_Plus_Gals__c = field.NewFloat64(table, "MTD_RTS_Plus_Gals__c")
	s.MTD_Total_Gals__c = field.NewFloat64(table, "MTD_Total_Gals__c")
	s.MTD_of_Transactions__c = field.NewFloat64(table, "MTD_of_Transactions__c")
	s.YTD_PFJ_Gals__c = field.NewFloat64(table, "YTD_PFJ_Gals__c")
	s.YTD_RTS_Plus_Gals__c = field.NewFloat64(table, "YTD_RTS_Plus_Gals__c")
	s.YTD_Total_Gals__c = field.NewFloat64(table, "YTD_Total_Gals__c")
	s.YTD_of_Transactions__c = field.NewFloat64(table, "YTD_of_Transactions__c")
	s.Implementation_Tier__c = field.NewString(table, "Implementation_Tier__c")
	s.Primary_Contact_Email__c = field.NewString(table, "Primary_Contact_Email__c")
	s.Primary_Contact_Phone__c = field.NewString(table, "Primary_Contact_Phone__c")
	s.MX_Number__c = field.NewString(table, "MX_Number__c")
	s.IFTA_Customer__c = field.NewBool(table, "IFTA_Customer__c")
	s.Alert_Tracking_Status__c = field.NewString(table, "Alert_Tracking_Status__c")
	s.RTSPT_WEB_Active_Customer__c = field.NewBool(table, "RTSPT_WEB_Active_Customer__c")
	s.RTSCS_Customer_Status__c = field.NewString(table, "RTSCS_Customer_Status__c")
	s.Alert_Date__c = field.NewTime(table, "Alert_Date__c")
	s.Alert_Type__c = field.NewString(table, "Alert_Type__c")
	s.PFJ_Ascend_Number__c = field.NewString(table, "PFJ_Ascend_Number__c")
	s.PFJ_Current_Wallet_Share__c = field.NewString(table, "PFJ_Current_Wallet_Share__c")
	s.PFJ_Customer_Status__c = field.NewString(table, "PFJ_Customer_Status__c")
	s.PFJ_Factoring_Competitor__c = field.NewString(table, "PFJ_Factoring_Competitor__c")
	s.STC_Transaction_Id__c = field.NewString(table, "STC_Transaction_Id__c")
	s.PFJ_Gallon_Alert__c = field.NewString(table, "PFJ_Gallon_Alert__c")
	s.PFJ_Gallon_Potential__c = field.NewString(table, "PFJ_Gallon_Potential__c")
	s.PFJ_Last_Month_Gallons__c = field.NewFloat64(table, "PFJ_Last_Month_Gallons__c")
	s.PFJ_Last_Update_Date_of_Fuel_History__c = field.NewString(table, "PFJ_Last_Update_Date_of_Fuel_History__c")
	s.PFJ_Last_Week_Gallons__c = field.NewFloat64(table, "PFJ_Last_Week_Gallons__c")
	s.PFJ_Min_Gallon_Amount__c = field.NewFloat64(table, "PFJ_Min_Gallon_Amount__c")
	s.PFJ_Min_Gallon_Percentage__c = field.NewFloat64(table, "PFJ_Min_Gallon_Percentage__c")
	s.PFJ_Number_of_Co_Trucks__c = field.NewFloat64(table, "PFJ_Number_of_Co_Trucks__c")
	s.PFJ_Number_of_Op_Trucks__c = field.NewFloat64(table, "PFJ_Number_of_Op_Trucks__c")
	s.PFJ_Number_of_Trucks__c = field.NewFloat64(table, "PFJ_Number_of_Trucks__c")
	s.PFJ_RTS_Eligible__c = field.NewString(table, "PFJ_RTS_Eligible__c")
	s.PFJ_RTS_Factoring_Notes__c = field.NewString(table, "PFJ_RTS_Factoring_Notes__c")
	s.PFJ_Rep_Email__c = field.NewString(table, "PFJ_Rep_Email__c")
	s.PFJ_Rep_Name__c = field.NewString(table, "PFJ_Rep_Name__c")
	s.PFJ_Rep_Phone__c = field.NewString(table, "PFJ_Rep_Phone__c")
	s.PFJ_Status__c = field.NewString(table, "PFJ_Status__c")
	s.PFJ_YTD_Gallons__c = field.NewFloat64(table, "PFJ_YTD_Gallons__c")
	s.Partner_Entity_ID__c = field.NewString(table, "Partner_Entity_ID__c")
	s.RTS_PFJ_Factoring_Notes__c = field.NewString(table, "RTS_PFJ_Factoring_Notes__c")
	s.RTSCS_Account_Manager__c = field.NewString(table, "RTSCS_Account_Manager__c")
	s.UCC_Filed_By__c = field.NewString(table, "UCC_Filed_By__c")
	s.PFJ_Factoring_Competitor_Rate__c = field.NewFloat64(table, "PFJ_Factoring_Competitor_Rate__c")
	s.LM_Cards_Used__c = field.NewFloat64(table, "LM_Cards_Used__c")
	s.MTD_Cards_Used__c = field.NewFloat64(table, "MTD_Cards_Used__c")
	s.YTD_Cards_Used__c = field.NewFloat64(table, "YTD_Cards_Used__c")
	s.FMCSA_Truck_Count__c = field.NewFloat64(table, "FMCSA_Truck_Count__c")
	s.Deal_Age_at_Alert__c = field.NewFloat64(table, "Deal_Age_at_Alert__c")
	s.Prior_30_Day_Volume__c = field.NewFloat64(table, "Prior_30_Day_Volume__c")
	s.Cadence_Active__c = field.NewBool(table, "Cadence_Active__c")
	s.Cadence_Balance__c = field.NewFloat64(table, "Cadence_Balance__c")
	s.Cadence_First_Funding_Date__c = field.NewTime(table, "Cadence_First_Funding_Date__c")
	s.Cadence_Fuel_Card_Group_Code__c = field.NewString(table, "Cadence_Fuel_Card_Group_Code__c")
	s.Cadence_Fuel_Status_Group_Code__c = field.NewString(table, "Cadence_Fuel_Status_Group_Code__c")
	s.Cadence_Last_Funding_Date__c = field.NewTime(table, "Cadence_Last_Funding_Date__c")
	s.Master_Factorsoft_Client_Number__c = field.NewString(table, "Master_Factorsoft_Client_Number__c")
	s.Pilot_Travel_Centers_LLC_Broker_Code__c = field.NewBool(table, "Pilot_Travel_Centers_LLC_Broker_Code__c")
	s.Software_Tier__c = field.NewString(table, "Software_Tier__c")
	s.UCC_Continued_Date__c = field.NewTime(table, "UCC_Continued_Date__c")
	s.Bundle_Status__c = field.NewString(table, "Bundle_Status__c")
	s.Compliance_Status__c = field.NewString(table, "Compliance_Status__c")
	s.MRA_Exception__c = field.NewString(table, "MRA_Exception__c")
	s.RTS_Pro_Last_Use__c = field.NewTime(table, "RTS_Pro_Last_Use__c")
	s.RTSF_Customer_Status__c = field.NewString(table, "RTSF_Customer_Status__c")
	s.RTSI_Customer_Status__c = field.NewString(table, "RTSI_Customer_Status__c")
	s.RTSPT_Customer_Status__c = field.NewString(table, "RTSPT_Customer_Status__c")
	s.RTSRT_Customer_Status__c = field.NewString(table, "RTSRT_Customer_Status__c")
	s.Truckers_Solution__c = field.NewBool(table, "Truckers_Solution__c")
	s.Authority_Status__c = field.NewString(table, "Authority_Status__c")
	s.RTSCS_Not_Eligible_Reason__c = field.NewString(table, "RTSCS_Not_Eligible_Reason__c")
	s.Bundle_Cards_Used_LM__c = field.NewFloat64(table, "Bundle_Cards_Used_LM__c")
	s.Bundle_Compliance__c = field.NewFloat64(table, "Bundle_Compliance__c")
	s.Bundle_Expected_LM_Gals__c = field.NewString(table, "Bundle_Expected_LM_Gals__c")
	s.Bundle_Grace_Period_End_Date__c = field.NewTime(table, "Bundle_Grace_Period_End_Date__c")
	s.Bundle_LM_Gallons__c = field.NewFloat64(table, "Bundle_LM_Gallons__c")
	s.MRA_LM_Volume__c = field.NewFloat64(table, "MRA_LM_Volume__c")
	s.ReplayId = field.NewString(table, "ReplayId")
	s.EntityName = field.NewString(table, "EntityName")
	s.Id = field.NewString(table, "Id")
	s.year = field.NewInt32(table, "year")
	s.month = field.NewInt32(table, "month")
	s.day = field.NewInt32(table, "day")
	s.hour = field.NewInt32(table, "hour")
	s._rescued_data = field.NewString(table, "_rescued_data")
	s.IsDeleted = field.NewBool(table, "IsDeleted")
	s.MasterRecordId = field.NewString(table, "MasterRecordId")
	s.PhotoUrl = field.NewString(table, "PhotoUrl")
	s.SystemModstamp = field.NewTime(table, "SystemModstamp")
	s.LastActivityDate = field.NewTime(table, "LastActivityDate")
	s.LastViewedDate = field.NewString(table, "LastViewedDate")
	s.LastReferencedDate = field.NewString(table, "LastReferencedDate")
	s.IsPartner = field.NewBool(table, "IsPartner")
	s.ChannelProgramName = field.NewString(table, "ChannelProgramName")
	s.ChannelProgramLevelName = field.NewString(table, "ChannelProgramLevelName")
	s.PersonActionCadenceId = field.NewString(table, "PersonActionCadenceId")
	s.PersonActionCadenceAssigneeId = field.NewString(table, "PersonActionCadenceAssigneeId")
	s.PersonActionCadenceState = field.NewString(table, "PersonActionCadenceState")
	s.PersonScheduledResumeDateTime = field.NewString(table, "PersonScheduledResumeDateTime")
	s.ActivityMetricId = field.NewString(table, "ActivityMetricId")
	s.RTSCS_Active_Customer__c = field.NewBool(table, "RTSCS_Active_Customer__c")
	s.RTSPT_Active_Customer__c = field.NewBool(table, "RTSPT_Active_Customer__c")
	s.FLT1_Gallon_Report__c = field.NewString(table, "FLT1_Gallon_Report__c")
	s.Partner_Gallon_Report__c = field.NewString(table, "Partner_Gallon_Report__c")
	s.Last_Activity_Date__c = field.NewTime(table, "Last_Activity_Date__c")
	s.LM_Partner_Gals__c = field.NewFloat64(table, "LM_Partner_Gals__c")
	s.MTD_Partner_Gals__c = field.NewFloat64(table, "MTD_Partner_Gals__c")
	s.YTD_Partner_Gals__c = field.NewFloat64(table, "YTD_Partner_Gals__c")
	s.RTSEF_Customer_Status__c = field.NewString(table, "RTSEF_Customer_Status__c")
	s.RTSEF_Not_Eligible_Reason__c = field.NewString(table, "RTSEF_Not_Eligible_Reason__c")
	s.BillingStreet = field.NewString(table, "BillingStreet")
	s.BillingCity = field.NewString(table, "BillingCity")
	s.BillingState = field.NewString(table, "BillingState")
	s.BillingPostalCode = field.NewString(table, "BillingPostalCode")
	s.BillingCountry = field.NewString(table, "BillingCountry")
	s.BillingStateCode = field.NewString(table, "BillingStateCode")
	s.BillingCountryCode = field.NewString(table, "BillingCountryCode")
	s.BillingLatitude = field.NewFloat64(table, "BillingLatitude")
	s.BillingLongitude = field.NewFloat64(table, "BillingLongitude")
	s.BillingGeocodeAccuracy = field.NewString(table, "BillingGeocodeAccuracy")
	s.ShippingStreet = field.NewString(table, "ShippingStreet")
	s.ShippingCity = field.NewString(table, "ShippingCity")
	s.ShippingState = field.NewString(table, "ShippingState")
	s.ShippingPostalCode = field.NewString(table, "ShippingPostalCode")
	s.ShippingCountry = field.NewString(table, "ShippingCountry")
	s.ShippingStateCode = field.NewString(table, "ShippingStateCode")
	s.ShippingCountryCode = field.NewString(table, "ShippingCountryCode")
	s.ShippingLatitude = field.NewFloat64(table, "ShippingLatitude")
	s.ShippingLongitude = field.NewFloat64(table, "ShippingLongitude")
	s.ShippingGeocodeAccuracy = field.NewString(table, "ShippingGeocodeAccuracy")

	s.fillFieldMap()

	return s
}

func (s *sfAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sfAccount) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 237)
	s.fieldMap["ChangeEventHeader"] = s.ChangeEventHeader
	s.fieldMap["Name"] = s.Name
	s.fieldMap["Type"] = s.Type
	s.fieldMap["RecordTypeId"] = s.RecordTypeId
	s.fieldMap["ParentId"] = s.ParentId
	s.fieldMap["Phone"] = s.Phone
	s.fieldMap["Fax"] = s.Fax
	s.fieldMap["AccountNumber"] = s.AccountNumber
	s.fieldMap["Website"] = s.Website
	s.fieldMap["Sic"] = s.Sic
	s.fieldMap["Industry"] = s.Industry
	s.fieldMap["AnnualRevenue"] = s.AnnualRevenue
	s.fieldMap["NumberOfEmployees"] = s.NumberOfEmployees
	s.fieldMap["Ownership"] = s.Ownership
	s.fieldMap["TickerSymbol"] = s.TickerSymbol
	s.fieldMap["Description"] = s.Description
	s.fieldMap["Rating"] = s.Rating
	s.fieldMap["Site"] = s.Site
	s.fieldMap["OwnerId"] = s.OwnerId
	s.fieldMap["CreatedDate"] = s.CreatedDate
	s.fieldMap["CreatedById"] = s.CreatedById
	s.fieldMap["LastModifiedDate"] = s.LastModifiedDate
	s.fieldMap["LastModifiedById"] = s.LastModifiedById
	s.fieldMap["SourceSystemIdentifier"] = s.SourceSystemIdentifier
	s.fieldMap["Jigsaw"] = s.Jigsaw
	s.fieldMap["JigsawCompanyId"] = s.JigsawCompanyId
	s.fieldMap["AccountSource"] = s.AccountSource
	s.fieldMap["SicDesc"] = s.SicDesc
	s.fieldMap["OperatingHoursId"] = s.OperatingHoursId
	s.fieldMap["IsPriorityRecord"] = s.IsPriorityRecord
	s.fieldMap["RTSF_Dormant_Reason__c"] = s.RTSF_Dormant_Reason__c
	s.fieldMap["Account_Legal_Name__c"] = s.Account_Legal_Name__c
	s.fieldMap["Carrier_Type__c"] = s.Carrier_Type__c
	s.fieldMap["Number_Of_Trucks__c"] = s.Number_Of_Trucks__c
	s.fieldMap["DOT_Number__c"] = s.DOT_Number__c
	s.fieldMap["MC_Number__c"] = s.MC_Number__c
	s.fieldMap["RTSF_Not_Eligible_Reason__c"] = s.RTSF_Not_Eligible_Reason__c
	s.fieldMap["Lead_Source__c"] = s.Lead_Source__c
	s.fieldMap["Primary_Contact__c"] = s.Primary_Contact__c
	s.fieldMap["RTSF_Active_Customer__c"] = s.RTSF_Active_Customer__c
	s.fieldMap["RTSI_Active_Customer__c"] = s.RTSI_Active_Customer__c
	s.fieldMap["OOIDA_Member_ID__c"] = s.OOIDA_Member_ID__c
	s.fieldMap["Region__c"] = s.Region__c
	s.fieldMap["RTSIN_Not_Eligible_Reason__c"] = s.RTSIN_Not_Eligible_Reason__c
	s.fieldMap["Outstanding_Pilot_Balance__c"] = s.Outstanding_Pilot_Balance__c
	s.fieldMap["CRM_Account_Number__c"] = s.CRM_Account_Number__c
	s.fieldMap["ProTransport_Cancellation_Reason__c"] = s.ProTransport_Cancellation_Reason__c
	s.fieldMap["ProTransport_Billing_On_Hold_Date__c"] = s.ProTransport_Billing_On_Hold_Date__c
	s.fieldMap["Language__c"] = s.Language__c
	s.fieldMap["maps__AssignmentRule__c"] = s.maps__AssignmentRule__c
	s.fieldMap["phone2__c"] = s.phone2__c
	s.fieldMap["RTSRT_Rep__c"] = s.RTSRT_Rep__c
	s.fieldMap["RTSF_Ops_Account_Rep__c"] = s.RTSF_Ops_Account_Rep__c
	s.fieldMap["SBQQ__AssetQuantitiesCombined__c"] = s.SBQQ__AssetQuantitiesCombined__c
	s.fieldMap["SBQQ__CoTermedContractsCombined__c"] = s.SBQQ__CoTermedContractsCombined__c
	s.fieldMap["SBQQ__CoTerminationEvent__c"] = s.SBQQ__CoTerminationEvent__c
	s.fieldMap["SBQQ__ContractCoTermination__c"] = s.SBQQ__ContractCoTermination__c
	s.fieldMap["SBQQ__DefaultOpportunity__c"] = s.SBQQ__DefaultOpportunity__c
	s.fieldMap["SBQQ__IgnoreParentContractedPrices__c"] = s.SBQQ__IgnoreParentContractedPrices__c
	s.fieldMap["SBQQ__PreserveBundle__c"] = s.SBQQ__PreserveBundle__c
	s.fieldMap["SBQQ__PriceHoldEnd__c"] = s.SBQQ__PriceHoldEnd__c
	s.fieldMap["SBQQ__RenewalModel__c"] = s.SBQQ__RenewalModel__c
	s.fieldMap["SBQQ__RenewalPricingMethod__c"] = s.SBQQ__RenewalPricingMethod__c
	s.fieldMap["SBQQ__TaxExempt__c"] = s.SBQQ__TaxExempt__c
	s.fieldMap["Account_Record_Type__c"] = s.Account_Record_Type__c
	s.fieldMap["Number_of_Fuel_Cards__c"] = s.Number_of_Fuel_Cards__c
	s.fieldMap["Has_FLT1__c"] = s.Has_FLT1__c
	s.fieldMap["RTSIN_Customer_Status__c"] = s.RTSIN_Customer_Status__c
	s.fieldMap["RTSCS_Rep__c"] = s.RTSCS_Rep__c
	s.fieldMap["RTSF_Rep__c"] = s.RTSF_Rep__c
	s.fieldMap["RTSI_Rep__c"] = s.RTSI_Rep__c
	s.fieldMap["RTS_Software_Rep__c"] = s.RTS_Software_Rep__c
	s.fieldMap["McLeod_Data__c"] = s.McLeod_Data__c
	s.fieldMap["Entity_Type__c"] = s.Entity_Type__c
	s.fieldMap["ProTransport_Account_Number__c"] = s.ProTransport_Account_Number__c
	s.fieldMap["RTSCS_Dormant_Reason__c"] = s.RTSCS_Dormant_Reason__c
	s.fieldMap["Active_Fuel_Cards__c"] = s.Active_Fuel_Cards__c
	s.fieldMap["CloudingoAgent__BAR__c"] = s.CloudingoAgent__BAR__c
	s.fieldMap["CloudingoAgent__BAS__c"] = s.CloudingoAgent__BAS__c
	s.fieldMap["ProTransport_Support__c"] = s.ProTransport_Support__c
	s.fieldMap["ProTransport_Version__c"] = s.ProTransport_Version__c
	s.fieldMap["RTS_Upload_Integration__c"] = s.RTS_Upload_Integration__c
	s.fieldMap["Using_EDI__c"] = s.Using_EDI__c
	s.fieldMap["Software__c"] = s.Software__c
	s.fieldMap["Hosted__c"] = s.Hosted__c
	s.fieldMap["RTSCS_On_Hold__c"] = s.RTSCS_On_Hold__c
	s.fieldMap["Trip_Management_Start_Date__c"] = s.Trip_Management_Start_Date__c
	s.fieldMap["Trip_Management__c"] = s.Trip_Management__c
	s.fieldMap["Citrix_User__c"] = s.Citrix_User__c
	s.fieldMap["CAB_ISS_Score__c"] = s.CAB_ISS_Score__c
	s.fieldMap["US_Veteran__c"] = s.US_Veteran__c
	s.fieldMap["CloudingoAgent__BAV__c"] = s.CloudingoAgent__BAV__c
	s.fieldMap["CloudingoAgent__BRDI__c"] = s.CloudingoAgent__BRDI__c
	s.fieldMap["CloudingoAgent__BTZ__c"] = s.CloudingoAgent__BTZ__c
	s.fieldMap["CloudingoAgent__SAR__c"] = s.CloudingoAgent__SAR__c
	s.fieldMap["CloudingoAgent__SAS__c"] = s.CloudingoAgent__SAS__c
	s.fieldMap["CloudingoAgent__SAV__c"] = s.CloudingoAgent__SAV__c
	s.fieldMap["CloudingoAgent__SRDI__c"] = s.CloudingoAgent__SRDI__c
	s.fieldMap["CloudingoAgent__STZ__c"] = s.CloudingoAgent__STZ__c
	s.fieldMap["Cancellation_Date__c"] = s.Cancellation_Date__c
	s.fieldMap["First_Fuel_Date__c"] = s.First_Fuel_Date__c
	s.fieldMap["LM_PFJ_Gals__c"] = s.LM_PFJ_Gals__c
	s.fieldMap["LM_RTS_Plus_Gals__c"] = s.LM_RTS_Plus_Gals__c
	s.fieldMap["LM_Total_Gals__c"] = s.LM_Total_Gals__c
	s.fieldMap["LM_of_Transactions__c"] = s.LM_of_Transactions__c
	s.fieldMap["Last_Fuel_Date__c"] = s.Last_Fuel_Date__c
	s.fieldMap["MTD_PFJ_Gals__c"] = s.MTD_PFJ_Gals__c
	s.fieldMap["MTD_RTS_Plus_Gals__c"] = s.MTD_RTS_Plus_Gals__c
	s.fieldMap["MTD_Total_Gals__c"] = s.MTD_Total_Gals__c
	s.fieldMap["MTD_of_Transactions__c"] = s.MTD_of_Transactions__c
	s.fieldMap["YTD_PFJ_Gals__c"] = s.YTD_PFJ_Gals__c
	s.fieldMap["YTD_RTS_Plus_Gals__c"] = s.YTD_RTS_Plus_Gals__c
	s.fieldMap["YTD_Total_Gals__c"] = s.YTD_Total_Gals__c
	s.fieldMap["YTD_of_Transactions__c"] = s.YTD_of_Transactions__c
	s.fieldMap["Implementation_Tier__c"] = s.Implementation_Tier__c
	s.fieldMap["Primary_Contact_Email__c"] = s.Primary_Contact_Email__c
	s.fieldMap["Primary_Contact_Phone__c"] = s.Primary_Contact_Phone__c
	s.fieldMap["MX_Number__c"] = s.MX_Number__c
	s.fieldMap["IFTA_Customer__c"] = s.IFTA_Customer__c
	s.fieldMap["Alert_Tracking_Status__c"] = s.Alert_Tracking_Status__c
	s.fieldMap["RTSPT_WEB_Active_Customer__c"] = s.RTSPT_WEB_Active_Customer__c
	s.fieldMap["RTSCS_Customer_Status__c"] = s.RTSCS_Customer_Status__c
	s.fieldMap["Alert_Date__c"] = s.Alert_Date__c
	s.fieldMap["Alert_Type__c"] = s.Alert_Type__c
	s.fieldMap["PFJ_Ascend_Number__c"] = s.PFJ_Ascend_Number__c
	s.fieldMap["PFJ_Current_Wallet_Share__c"] = s.PFJ_Current_Wallet_Share__c
	s.fieldMap["PFJ_Customer_Status__c"] = s.PFJ_Customer_Status__c
	s.fieldMap["PFJ_Factoring_Competitor__c"] = s.PFJ_Factoring_Competitor__c
	s.fieldMap["STC_Transaction_Id__c"] = s.STC_Transaction_Id__c
	s.fieldMap["PFJ_Gallon_Alert__c"] = s.PFJ_Gallon_Alert__c
	s.fieldMap["PFJ_Gallon_Potential__c"] = s.PFJ_Gallon_Potential__c
	s.fieldMap["PFJ_Last_Month_Gallons__c"] = s.PFJ_Last_Month_Gallons__c
	s.fieldMap["PFJ_Last_Update_Date_of_Fuel_History__c"] = s.PFJ_Last_Update_Date_of_Fuel_History__c
	s.fieldMap["PFJ_Last_Week_Gallons__c"] = s.PFJ_Last_Week_Gallons__c
	s.fieldMap["PFJ_Min_Gallon_Amount__c"] = s.PFJ_Min_Gallon_Amount__c
	s.fieldMap["PFJ_Min_Gallon_Percentage__c"] = s.PFJ_Min_Gallon_Percentage__c
	s.fieldMap["PFJ_Number_of_Co_Trucks__c"] = s.PFJ_Number_of_Co_Trucks__c
	s.fieldMap["PFJ_Number_of_Op_Trucks__c"] = s.PFJ_Number_of_Op_Trucks__c
	s.fieldMap["PFJ_Number_of_Trucks__c"] = s.PFJ_Number_of_Trucks__c
	s.fieldMap["PFJ_RTS_Eligible__c"] = s.PFJ_RTS_Eligible__c
	s.fieldMap["PFJ_RTS_Factoring_Notes__c"] = s.PFJ_RTS_Factoring_Notes__c
	s.fieldMap["PFJ_Rep_Email__c"] = s.PFJ_Rep_Email__c
	s.fieldMap["PFJ_Rep_Name__c"] = s.PFJ_Rep_Name__c
	s.fieldMap["PFJ_Rep_Phone__c"] = s.PFJ_Rep_Phone__c
	s.fieldMap["PFJ_Status__c"] = s.PFJ_Status__c
	s.fieldMap["PFJ_YTD_Gallons__c"] = s.PFJ_YTD_Gallons__c
	s.fieldMap["Partner_Entity_ID__c"] = s.Partner_Entity_ID__c
	s.fieldMap["RTS_PFJ_Factoring_Notes__c"] = s.RTS_PFJ_Factoring_Notes__c
	s.fieldMap["RTSCS_Account_Manager__c"] = s.RTSCS_Account_Manager__c
	s.fieldMap["UCC_Filed_By__c"] = s.UCC_Filed_By__c
	s.fieldMap["PFJ_Factoring_Competitor_Rate__c"] = s.PFJ_Factoring_Competitor_Rate__c
	s.fieldMap["LM_Cards_Used__c"] = s.LM_Cards_Used__c
	s.fieldMap["MTD_Cards_Used__c"] = s.MTD_Cards_Used__c
	s.fieldMap["YTD_Cards_Used__c"] = s.YTD_Cards_Used__c
	s.fieldMap["FMCSA_Truck_Count__c"] = s.FMCSA_Truck_Count__c
	s.fieldMap["Deal_Age_at_Alert__c"] = s.Deal_Age_at_Alert__c
	s.fieldMap["Prior_30_Day_Volume__c"] = s.Prior_30_Day_Volume__c
	s.fieldMap["Cadence_Active__c"] = s.Cadence_Active__c
	s.fieldMap["Cadence_Balance__c"] = s.Cadence_Balance__c
	s.fieldMap["Cadence_First_Funding_Date__c"] = s.Cadence_First_Funding_Date__c
	s.fieldMap["Cadence_Fuel_Card_Group_Code__c"] = s.Cadence_Fuel_Card_Group_Code__c
	s.fieldMap["Cadence_Fuel_Status_Group_Code__c"] = s.Cadence_Fuel_Status_Group_Code__c
	s.fieldMap["Cadence_Last_Funding_Date__c"] = s.Cadence_Last_Funding_Date__c
	s.fieldMap["Master_Factorsoft_Client_Number__c"] = s.Master_Factorsoft_Client_Number__c
	s.fieldMap["Pilot_Travel_Centers_LLC_Broker_Code__c"] = s.Pilot_Travel_Centers_LLC_Broker_Code__c
	s.fieldMap["Software_Tier__c"] = s.Software_Tier__c
	s.fieldMap["UCC_Continued_Date__c"] = s.UCC_Continued_Date__c
	s.fieldMap["Bundle_Status__c"] = s.Bundle_Status__c
	s.fieldMap["Compliance_Status__c"] = s.Compliance_Status__c
	s.fieldMap["MRA_Exception__c"] = s.MRA_Exception__c
	s.fieldMap["RTS_Pro_Last_Use__c"] = s.RTS_Pro_Last_Use__c
	s.fieldMap["RTSF_Customer_Status__c"] = s.RTSF_Customer_Status__c
	s.fieldMap["RTSI_Customer_Status__c"] = s.RTSI_Customer_Status__c
	s.fieldMap["RTSPT_Customer_Status__c"] = s.RTSPT_Customer_Status__c
	s.fieldMap["RTSRT_Customer_Status__c"] = s.RTSRT_Customer_Status__c
	s.fieldMap["Truckers_Solution__c"] = s.Truckers_Solution__c
	s.fieldMap["Authority_Status__c"] = s.Authority_Status__c
	s.fieldMap["RTSCS_Not_Eligible_Reason__c"] = s.RTSCS_Not_Eligible_Reason__c
	s.fieldMap["Bundle_Cards_Used_LM__c"] = s.Bundle_Cards_Used_LM__c
	s.fieldMap["Bundle_Compliance__c"] = s.Bundle_Compliance__c
	s.fieldMap["Bundle_Expected_LM_Gals__c"] = s.Bundle_Expected_LM_Gals__c
	s.fieldMap["Bundle_Grace_Period_End_Date__c"] = s.Bundle_Grace_Period_End_Date__c
	s.fieldMap["Bundle_LM_Gallons__c"] = s.Bundle_LM_Gallons__c
	s.fieldMap["MRA_LM_Volume__c"] = s.MRA_LM_Volume__c
	s.fieldMap["ReplayId"] = s.ReplayId
	s.fieldMap["EntityName"] = s.EntityName
	s.fieldMap["Id"] = s.Id
	s.fieldMap["year"] = s.year
	s.fieldMap["month"] = s.month
	s.fieldMap["day"] = s.day
	s.fieldMap["hour"] = s.hour
	s.fieldMap["_rescued_data"] = s._rescued_data
	s.fieldMap["IsDeleted"] = s.IsDeleted
	s.fieldMap["MasterRecordId"] = s.MasterRecordId
	s.fieldMap["PhotoUrl"] = s.PhotoUrl
	s.fieldMap["SystemModstamp"] = s.SystemModstamp
	s.fieldMap["LastActivityDate"] = s.LastActivityDate
	s.fieldMap["LastViewedDate"] = s.LastViewedDate
	s.fieldMap["LastReferencedDate"] = s.LastReferencedDate
	s.fieldMap["IsPartner"] = s.IsPartner
	s.fieldMap["ChannelProgramName"] = s.ChannelProgramName
	s.fieldMap["ChannelProgramLevelName"] = s.ChannelProgramLevelName
	s.fieldMap["PersonActionCadenceId"] = s.PersonActionCadenceId
	s.fieldMap["PersonActionCadenceAssigneeId"] = s.PersonActionCadenceAssigneeId
	s.fieldMap["PersonActionCadenceState"] = s.PersonActionCadenceState
	s.fieldMap["PersonScheduledResumeDateTime"] = s.PersonScheduledResumeDateTime
	s.fieldMap["ActivityMetricId"] = s.ActivityMetricId
	s.fieldMap["RTSCS_Active_Customer__c"] = s.RTSCS_Active_Customer__c
	s.fieldMap["RTSPT_Active_Customer__c"] = s.RTSPT_Active_Customer__c
	s.fieldMap["FLT1_Gallon_Report__c"] = s.FLT1_Gallon_Report__c
	s.fieldMap["Partner_Gallon_Report__c"] = s.Partner_Gallon_Report__c
	s.fieldMap["Last_Activity_Date__c"] = s.Last_Activity_Date__c
	s.fieldMap["LM_Partner_Gals__c"] = s.LM_Partner_Gals__c
	s.fieldMap["MTD_Partner_Gals__c"] = s.MTD_Partner_Gals__c
	s.fieldMap["YTD_Partner_Gals__c"] = s.YTD_Partner_Gals__c
	s.fieldMap["RTSEF_Customer_Status__c"] = s.RTSEF_Customer_Status__c
	s.fieldMap["RTSEF_Not_Eligible_Reason__c"] = s.RTSEF_Not_Eligible_Reason__c
	s.fieldMap["BillingStreet"] = s.BillingStreet
	s.fieldMap["BillingCity"] = s.BillingCity
	s.fieldMap["BillingState"] = s.BillingState
	s.fieldMap["BillingPostalCode"] = s.BillingPostalCode
	s.fieldMap["BillingCountry"] = s.BillingCountry
	s.fieldMap["BillingStateCode"] = s.BillingStateCode
	s.fieldMap["BillingCountryCode"] = s.BillingCountryCode
	s.fieldMap["BillingLatitude"] = s.BillingLatitude
	s.fieldMap["BillingLongitude"] = s.BillingLongitude
	s.fieldMap["BillingGeocodeAccuracy"] = s.BillingGeocodeAccuracy
	s.fieldMap["ShippingStreet"] = s.ShippingStreet
	s.fieldMap["ShippingCity"] = s.ShippingCity
	s.fieldMap["ShippingState"] = s.ShippingState
	s.fieldMap["ShippingPostalCode"] = s.ShippingPostalCode
	s.fieldMap["ShippingCountry"] = s.ShippingCountry
	s.fieldMap["ShippingStateCode"] = s.ShippingStateCode
	s.fieldMap["ShippingCountryCode"] = s.ShippingCountryCode
	s.fieldMap["ShippingLatitude"] = s.ShippingLatitude
	s.fieldMap["ShippingLongitude"] = s.ShippingLongitude
	s.fieldMap["ShippingGeocodeAccuracy"] = s.ShippingGeocodeAccuracy
}

func (s sfAccount) clone(db *gorm.DB) sfAccount {
	s.sfAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sfAccount) replaceDB(db *gorm.DB) sfAccount {
	s.sfAccountDo.ReplaceDB(db)
	return s
}

type sfAccountDo struct{ gen.DO }

type ISfAccountDo interface {
	gen.SubQuery
	Debug() ISfAccountDo
	WithContext(ctx context.Context) ISfAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISfAccountDo
	WriteDB() ISfAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISfAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISfAccountDo
	Not(conds ...gen.Condition) ISfAccountDo
	Or(conds ...gen.Condition) ISfAccountDo
	Select(conds ...field.Expr) ISfAccountDo
	Where(conds ...gen.Condition) ISfAccountDo
	Order(conds ...field.Expr) ISfAccountDo
	Distinct(cols ...field.Expr) ISfAccountDo
	Omit(cols ...field.Expr) ISfAccountDo
	Join(table schema.Tabler, on ...field.Expr) ISfAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISfAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISfAccountDo
	Group(cols ...field.Expr) ISfAccountDo
	Having(conds ...gen.Condition) ISfAccountDo
	Limit(limit int) ISfAccountDo
	Offset(offset int) ISfAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISfAccountDo
	Unscoped() ISfAccountDo
	Create(values ...*model.SfAccount) error
	CreateInBatches(values []*model.SfAccount, batchSize int) error
	Save(values ...*model.SfAccount) error
	First() (*model.SfAccount, error)
	Take() (*model.SfAccount, error)
	Last() (*model.SfAccount, error)
	Find() ([]*model.SfAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SfAccount, err error)
	FindInBatches(result *[]*model.SfAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SfAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISfAccountDo
	Assign(attrs ...field.AssignExpr) ISfAccountDo
	Joins(fields ...field.RelationField) ISfAccountDo
	Preload(fields ...field.RelationField) ISfAccountDo
	FirstOrInit() (*model.SfAccount, error)
	FirstOrCreate() (*model.SfAccount, error)
	FindByPage(offset int, limit int) (result []*model.SfAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISfAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithColumn(column string, value string) (result model.SfAccount, err error)
}

// SELECT * FROM @@table WHERE @@column=@value
func (s sfAccountDo) FilterWithColumn(column string, value string) (result model.SfAccount, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, value)
	generateSQL.WriteString("SELECT * FROM sf_account WHERE " + s.Quote(column) + "=? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s sfAccountDo) Debug() ISfAccountDo {
	return s.withDO(s.DO.Debug())
}

func (s sfAccountDo) WithContext(ctx context.Context) ISfAccountDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sfAccountDo) ReadDB() ISfAccountDo {
	return s.Clauses(dbresolver.Read)
}

func (s sfAccountDo) WriteDB() ISfAccountDo {
	return s.Clauses(dbresolver.Write)
}

func (s sfAccountDo) Session(config *gorm.Session) ISfAccountDo {
	return s.withDO(s.DO.Session(config))
}

func (s sfAccountDo) Clauses(conds ...clause.Expression) ISfAccountDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sfAccountDo) Returning(value interface{}, columns ...string) ISfAccountDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sfAccountDo) Not(conds ...gen.Condition) ISfAccountDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sfAccountDo) Or(conds ...gen.Condition) ISfAccountDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sfAccountDo) Select(conds ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sfAccountDo) Where(conds ...gen.Condition) ISfAccountDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sfAccountDo) Order(conds ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sfAccountDo) Distinct(cols ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sfAccountDo) Omit(cols ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sfAccountDo) Join(table schema.Tabler, on ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sfAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sfAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sfAccountDo) Group(cols ...field.Expr) ISfAccountDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sfAccountDo) Having(conds ...gen.Condition) ISfAccountDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sfAccountDo) Limit(limit int) ISfAccountDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sfAccountDo) Offset(offset int) ISfAccountDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sfAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISfAccountDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sfAccountDo) Unscoped() ISfAccountDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sfAccountDo) Create(values ...*model.SfAccount) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sfAccountDo) CreateInBatches(values []*model.SfAccount, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sfAccountDo) Save(values ...*model.SfAccount) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sfAccountDo) First() (*model.SfAccount, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SfAccount), nil
	}
}

func (s sfAccountDo) Take() (*model.SfAccount, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SfAccount), nil
	}
}

func (s sfAccountDo) Last() (*model.SfAccount, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SfAccount), nil
	}
}

func (s sfAccountDo) Find() ([]*model.SfAccount, error) {
	result, err := s.DO.Find()
	return result.([]*model.SfAccount), err
}

func (s sfAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SfAccount, err error) {
	buf := make([]*model.SfAccount, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sfAccountDo) FindInBatches(result *[]*model.SfAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sfAccountDo) Attrs(attrs ...field.AssignExpr) ISfAccountDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sfAccountDo) Assign(attrs ...field.AssignExpr) ISfAccountDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sfAccountDo) Joins(fields ...field.RelationField) ISfAccountDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sfAccountDo) Preload(fields ...field.RelationField) ISfAccountDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sfAccountDo) FirstOrInit() (*model.SfAccount, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SfAccount), nil
	}
}

func (s sfAccountDo) FirstOrCreate() (*model.SfAccount, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SfAccount), nil
	}
}

func (s sfAccountDo) FindByPage(offset int, limit int) (result []*model.SfAccount, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sfAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sfAccountDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sfAccountDo) Delete(models ...*model.SfAccount) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sfAccountDo) withDO(do gen.Dao) *sfAccountDo {
	s.DO = *do.(*gen.DO)
	return s
}
